-- MySQL Script generated by MySQL Workbench
-- Sun Aug 12 18:53:24 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema logs
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema safetycc
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `safetycc` ;

-- -----------------------------------------------------
-- Schema safetycc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `safetycc` DEFAULT CHARACTER SET utf8 ;
USE `safetycc` ;

-- -----------------------------------------------------
-- Table `safetycc`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safetycc`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(60) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `password` VARCHAR(80) NOT NULL,
  `token` VARCHAR(80) NULL,
  `arduino` VARCHAR(200) NULL,
  `modernize` DATETIME NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `safetycc`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safetycc`.`logs` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `users_id` INT(11) NOT NULL,
  `arduino` VARCHAR(200) NOT NULL,
  `registry` DATETIME NOT NULL DEFAULT now(),
  PRIMARY KEY (`id`),
  INDEX `fk_logs_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_logs_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `safetycc`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `safetycc`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `safetycc`;
INSERT INTO `safetycc`.`users` (`id`, `name`, `email`, `password`, `token`, `arduino`, `modernize`) VALUES (1, 'Uniceub', 'uniceub@gmail.com', '123456', NULL, NULL, NULL);

COMMIT;

